### ISSUE TITLE
Downloading the full citation network?

### ISSUE THREAD

**Issue by dhimmel** [essepuntato/opencitations#1]
I was really excited to learn of OpenCitations -- I've been crossing my fingers for a while now for a CC0 network of publication references.

Where can I download the full database?

**Comment by essepuntato** [comment]
Hi,

The full citation network currently available (it is continuously populated day by day!) will be available by the first days of September. We will announce it in the website (http://opencitations.net) and in our Twitter account (@opencitations).

Happy you like the project :-)

**Comment by essepuntato** [comment]
Hi @dhimmel 

The dump is now available at http://opencitations.net/download
