### ISSUE TITLE
Clarify software license information

### ISSUE THREAD

**Issue by zuphilip** [essepuntato/opencitations#2]
You mentioned in the mail to wikicite a ISC Licence for the Open Source Software here, but I cannot see any mention here.

**Comment by essepuntato** [comment]
I avoided to add it in the main dir of the repo because it actually contains several kinds of documents - some are codes, others are ontologies, others are papers, etc.

The indication of the license is added in comments in each file.

**Comment by zuphilip** [comment]
Is the ISC license not anyway restricted to the code? It reads: "Permission to use, copy, modify, and/or distribute **this software** [...]".

However, you could clarify exactly what you want to cover in the README file, cf. for example https://github.com/openstreetmap/iD#license . Maybe, write something like "The software here is available under the ISC License, but this does not cover the papers or ontology."

The current drawback is that I would have to check every file separately how it is licensed.

BTW are there any restrictions to re-use the ontology?

**Comment by essepuntato** [comment]
Hi @zuphilip,

Sorry to be so late in answering you. I've just added the license statement as you suggested, thanks!

About the ontology, they are covered with a CC-BY license, thus are freely reusable in any context.

**Comment by zuphilip** [comment]
Thank you very much!
